# web port
server:
  #port: ${server.port}
  port: 9101

# log config
logging:
  config: classpath:logback.xml
  #path: ${data.path}/applogs/executor/jobhandler
  path: ./logs/executor/jobhandler

datax:
  job:
    admin:
      ### datax admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:8090
      #addresses: http://127.0.0.1:${datax.admin.port}
    executor:
      appname: datax-executor
      ip:
      port: 9001
      #port: ${executor.port:9999}
      ### job log path
      logpath: ./logs/executor/jobhandler
      #logpath: ${data.path}/applogs/executor/jobhandler
      ### job log retention days
      logretentiondays: 30
    ### job, access token
    accessToken:

  executor:
    jsonpath: D:\\datax\\job\\
    #jsonpath: ${json.path}

  pypath: D:\\datax\\bin\\datax.py
  #pypath: ${python.path}